# Generated by Django 4.2.15 on 2024-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('batch_size', models.IntegerField()),
                ('guidance_scale', models.FloatField()),
                ('render_mode', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
