# Generated by Django 4.2.15 on 2024-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelGenerate3D', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='time',
            field=models.CharField(default='2024_11_26 19_44_57', max_length=80),
            preserve_default=False,
        ),
    ]
